#This page will let us to test our API and see if works. 
POST http://127.0.0.1:8000/create_company_account HTTP/1.1
Content-Type: application/json

{ 
 "Company_Name"            :   "Company2",
 "Company_AddressCountry"  :   "Country3",
 "Company_AddressState"    :   "State3",
 "Company_AddressCity"     :   "City3",
 "Company_AddressStreet"   :   "street3",
 "Company_AddressNumber"   :   "number3",
 "Company_AddressPostCode" :   "postcode3",
 "Company_VATID"           :   "vatid2",
 "Company_BankAccName"     :   "bank3",
 "Company_BankAccNumber"   :   "banknumber3"
}
####
#


POST http://127.0.0.1:8000/create_customer_account HTTP/1.1
Content-Type: application/json


{
 "Customer_Email"                   : "email2@gmail.com",
 "Customer_Birthdate"               :"2000-01-01",
 "Customer_Name"                    : "name4",
 "Customer_Surname"                 : "surname4",
 "Customer_AddressCountry"          : "country4",
 "Customer_AddressState"            : "state4",
 "Customer_AddressCity"             : "city4",
 "Customer_AddressStreet"           : "street4",
 "Customer_AddressNumber"           : "number4",
 "Customer_AddressPostCode"         : "postcode4",
 "Customer_CCNumber"                : "56022266748153064"
}
###

#56022266748153064

POST http://127.0.0.1:8000/create_product HTTP/1.1
Content-Type: application/json

{
 "Product_Name"               : "product2",
 "Product_CurrencyCode"       : "USD",
 "Product_Price"              : "2",
 "Company_VATID"              : "vatid1"
}

###


POST http://127.0.0.1:8000/create_quote HTTP/1.1
Content-Type: application/json

{
 "Product_ID"                   : "2",
 "Quote_Quantity"               : "4",
 "Quote_Date"                   : "2021-01-04",
 "Customer_Email"               : "email2@gmail.com"
}

###


POST http://127.0.0.1:8000/accept_quote HTTP/1.1
Content-Type: application/json

{
 "Quote_ID"               : "1",
 "Customer_ID"              : "1"
}
###


POST http://127.0.0.1:8000/create_invoice HTTP/1.1
Content-Type: application/json

{
 "Customer_ID"              : "1",
 "Subscription_ID"          : "1"
}
###




POST http://127.0.0.1:8000/update_invoice HTTP/1.1
Content-Type: application/json

{
 "Customer_ID"              : "2",
 "Subscription_ID"          : "1",
 "Invoice_PaidDate"         : "2021-01-02"
}
###




GET http://127.0.0.1:8000/ask_mrr HTTP/1.1
Content-Type: application/json

{
    "Company_ID" : "1"
}

###



GET http://127.0.0.1:8000/ask_arr HTTP/1.1
Content-Type: application/json

{
    "Company_ID" : "1"
}

###




GET http://127.0.0.1:8000/number_of_customers_and_revenue HTTP/1.1
Content-Type: application/json

{
    "Company_ID" : "1"
}

###





GET http://127.0.0.1:8000/customers_all HTTP/1.1
Content-Type: application/json

{
    "Subscription_Active" : "1"
}

###











#-----------------------------EXTRA STUFF 


GET http://127.0.0.1:8000/see_customer_account HTTP/1.1
Content-Type: application/json

{
    "Customer_Email" : "email3@gmail.com"
}

###