#This page will let us to test our API and see if works. 
POST http://127.0.0.1:8000/create_company_account HTTP/1.1
Content-Type: application/json

{ 
 "Company_Name"            :   "newcomtest1",
 "Company_AddressCountry"  :   "USA",
 "Company_AddressState"    :   "LA",
 "Company_AddressCity"     :   "sillicon",
 "Company_AddressStreet"   :   "BeautifulStreet",
 "Company_AddressNumber"   :   "546",
 "Company_AddressPostCode" :   "10200",
 "Company_VATID"           :   "aaaaa",
 "Company_BankAccName"     :   "MetaCorp",
 "Company_BankAccNumber"   :   "1225345345345"
}
####
#


POST http://127.0.0.1:8000/create_customer_account HTTP/1.1
Content-Type: application/json


{
 "Customer_Email"                : "newemailtest@gmail.com",
 "Customer_Name"                 : "testname",
 "Customer_Surname"              : "testsurname",
 "Customer_AddressCountry"       : "test countrory",
 "Customer_AddressState"         : "test state",
 "Customer_AddressCity"          : "test city",
 "Customer_AddressStreet"        : "test street",
 "Customer_AddressNumber"        : "123123 ",
 "Customer_AddressPostCode"      : "1231231",
 "Customer_CCNumber"             : "56022266748153064"
}
###

POST http://127.0.0.1:8000/create_quote HTTP/1.1
Content-Type: application/json

{
 "Product_Name"               : "testproduct",
 "Product_CurrencyCode"       : "GBP",
 "Product_Price"              : "20",
 "Company_ID"                 : "1",
 "Quote_Quantity"             : "2",
 "Quote_Date"                 : "3003-01-02",
 "Customer_Email"             : "email1@gmail.com"
}

###


POST http://127.0.0.1:8000/accept_quote HTTP/1.1
Content-Type: application/json

{
 "Product_ID"               : "1",
 "Customer_ID"              : "1"
}
###